/**
 * Dextinity - Roblox Studio Export System
 *
 * Packages generated code into a downloadable ZIP with proper
 * Roblox folder structure and import instructions.
 * Also generates .rbxmx (Roblox Model XML) for direct import.
 */

export class RobloxExporter {
  /**
   * Export the project as a downloadable ZIP.
   * @param {object} project - The full project context from the chain
   * @returns {Promise<Blob>} ZIP file as a Blob
   */
  async exportZip(project) {
    // JSZip is loaded from CDN in the HTML
    const zip = new JSZip();
    const files = project.files || [];
    const gameTitle = project.gameTitle || 'DextinityGame';

    // Root folder
    const root = zip.folder(gameTitle);

    // Add all Luau files
    for (const file of files) {
      root.file(file.path, file.luau || '-- Empty file');
    }

    // Add Antigravity source files in a separate folder
    const agSrc = root.folder('_antigravity_source');
    for (const file of files) {
      if (file.antigravity) {
        const agPath = file.path.replace(/\.lua$/, '.ag');
        agSrc.file(agPath, file.antigravity);
      }
    }

    // Add project manifest
    const manifest = {
      name: gameTitle,
      type: project.gameType,
      coreLoop: project.coreLoop,
      generatedAt: new Date().toISOString(),
      generator: 'Dextinity',
      files: files.map(f => ({
        path: f.path,
        scriptType: f.scriptType,
        description: f.description,
      })),
      systems: project.plan?.systems || [],
      testScores: project.testResults?.overallScore || {},
    };
    root.file('dextinity-manifest.json', JSON.stringify(manifest, null, 2));

    // Add README with import instructions
    const readme = this._generateReadme(project);
    root.file('README.md', readme);

    // Add Rojo project file for Rojo users
    const rojoProject = this._generateRojoProject(project);
    root.file('default.project.json', JSON.stringify(rojoProject, null, 2));

    // Generate and add .rbxmx model files
    const rbxmx = this._generateRbxmx(project);
    root.file(`${gameTitle}.rbxmx`, rbxmx);

    return zip.generateAsync({ type: 'blob' });
  }

  /**
   * Generate README with Roblox Studio import instructions.
   */
  _generateReadme(project) {
    const gameTitle = project.gameTitle || 'DextinityGame';
    const files = project.files || [];

    const serverFiles = files.filter(f => f.scriptType === 'Script');
    const clientFiles = files.filter(f => f.scriptType === 'LocalScript');
    const moduleFiles = files.filter(f => f.scriptType === 'ModuleScript');

    return `# ${gameTitle}
Generated by Dextinity - Autonomous Roblox Game Development

## Game Info
- **Type:** ${project.gameType || 'Custom'}
- **Core Loop:** ${project.coreLoop || 'N/A'}
- **Files:** ${files.length} total (${serverFiles.length} server, ${clientFiles.length} client, ${moduleFiles.length} shared)

## Import to Roblox Studio

### Method 1: Manual Import
1. Open Roblox Studio and create a new Baseplate place
2. For each file in the project:

**Server Scripts** (place in ServerScriptService):
${serverFiles.map(f => `   - \`${f.path}\` - ${f.description}`).join('\n')}

**Client Scripts** (place in StarterPlayer > StarterPlayerScripts):
${clientFiles.map(f => `   - \`${f.path}\` - ${f.description}`).join('\n')}

**Shared Modules** (place in ReplicatedStorage):
${moduleFiles.map(f => `   - \`${f.path}\` - ${f.description}`).join('\n')}

3. Create the folder structure matching the file paths
4. Copy-paste each .lua file's contents into the corresponding Script/LocalScript/ModuleScript
5. Create a folder called "Remotes" in ReplicatedStorage and add RemoteEvent/RemoteFunction objects as needed

### Method 2: Using Rojo (Recommended)
1. Install Rojo: https://rojo.space
2. Open a terminal in this project folder
3. Run: \`rojo serve default.project.json\`
4. In Roblox Studio, connect to the Rojo server
5. All files will sync automatically

### Method 3: RBXMX Import
1. Open Roblox Studio
2. Right-click on the target service (ServerScriptService, etc.)
3. Select "Insert from File"
4. Choose the \`${gameTitle}.rbxmx\` file

## File Structure
\`\`\`
${files.map(f => f.path).join('\n')}
\`\`\`

## Systems
${(project.plan?.systems || []).map(s => `- **${s.name}** (${s.type}): ${s.description}`).join('\n')}

## Test Results
${project.testResults?.overallScore ? `
- Functionality: ${project.testResults.overallScore.functionality}/10
- Security: ${project.testResults.overallScore.security}/10
- Performance: ${project.testResults.overallScore.performance}/10
- Code Quality: ${project.testResults.overallScore.codeQuality}/10
` : 'No test results available'}

---
Generated by Dextinity on ${new Date().toISOString()}
`;
  }

  /**
   * Generate a Rojo project file for syncing with Roblox Studio.
   */
  _generateRojoProject(project) {
    const gameTitle = project.gameTitle || 'DextinityGame';

    return {
      name: gameTitle,
      tree: {
        $className: 'DataModel',
        ServerScriptService: {
          $className: 'ServerScriptService',
          Server: {
            $path: 'ServerScriptService/Server',
          },
        },
        StarterPlayer: {
          $className: 'StarterPlayer',
          StarterPlayerScripts: {
            $className: 'StarterPlayerScripts',
            Client: {
              $path: 'StarterPlayer/StarterPlayerScripts/Client',
            },
          },
        },
        ReplicatedStorage: {
          $className: 'ReplicatedStorage',
          Shared: {
            $path: 'ReplicatedStorage/Shared',
          },
          Remotes: {
            $className: 'Folder',
          },
        },
        StarterGui: {
          $className: 'StarterGui',
        },
      },
    };
  }

  /**
   * Generate a .rbxmx (Roblox Model XML) file for direct import.
   */
  _generateRbxmx(project) {
    const files = project.files || [];
    let refId = 0;

    const escapeXml = (str) => {
      return (str || '')
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&apos;');
    };

    const makeScript = (file) => {
      const className = file.scriptType === 'Script' ? 'Script'
        : file.scriptType === 'LocalScript' ? 'LocalScript'
        : 'ModuleScript';
      const name = file.path.split('/').pop().replace(/\.(server|client)?\.lua$/, '');
      refId++;

      return `  <Item class="${className}" referent="RBX${refId}">
    <Properties>
      <string name="Name">${escapeXml(name)}</string>
      <ProtectedString name="Source"><![CDATA[${file.luau || ''}]]></ProtectedString>
    </Properties>
  </Item>`;
    };

    const serverScripts = files
      .filter(f => f.scriptType === 'Script')
      .map(makeScript)
      .join('\n');

    const clientScripts = files
      .filter(f => f.scriptType === 'LocalScript')
      .map(makeScript)
      .join('\n');

    const moduleScripts = files
      .filter(f => f.scriptType === 'ModuleScript')
      .map(makeScript)
      .join('\n');

    return `<roblox version="4">
<Item class="Folder" referent="RBX0">
  <Properties>
    <string name="Name">ServerScripts</string>
  </Properties>
${serverScripts}
</Item>
<Item class="Folder" referent="RBXC0">
  <Properties>
    <string name="Name">ClientScripts</string>
  </Properties>
${clientScripts}
</Item>
<Item class="Folder" referent="RBXM0">
  <Properties>
    <string name="Name">SharedModules</string>
  </Properties>
${moduleScripts}
</Item>
</roblox>`;
  }

  /**
   * Build the file tree structure for UI display.
   */
  buildFileTree(files) {
    const tree = {};

    for (const file of files) {
      const parts = file.path.split('/');
      let current = tree;

      for (let i = 0; i < parts.length; i++) {
        const part = parts[i];
        if (i === parts.length - 1) {
          // File
          current[part] = {
            type: 'file',
            scriptType: file.scriptType,
            path: file.path,
          };
        } else {
          // Folder
          if (!current[part]) {
            current[part] = { type: 'folder', children: {} };
          }
          current = current[part].children;
        }
      }
    }

    return tree;
  }

  /**
   * Build the structure view for UI display.
   */
  buildStructureView(project) {
    const items = [];
    const files = project.files || [];

    // Group by Roblox service
    const groups = {
      'ServerScriptService': files.filter(f => f.path.startsWith('ServerScriptService')),
      'StarterPlayer': files.filter(f => f.path.startsWith('StarterPlayer')),
      'ReplicatedStorage': files.filter(f => f.path.startsWith('ReplicatedStorage')),
      'StarterGui': files.filter(f => f.path.startsWith('StarterGui')),
      'Other': files.filter(f =>
        !f.path.startsWith('ServerScriptService') &&
        !f.path.startsWith('StarterPlayer') &&
        !f.path.startsWith('ReplicatedStorage') &&
        !f.path.startsWith('StarterGui')
      ),
    };

    for (const [service, serviceFiles] of Object.entries(groups)) {
      if (serviceFiles.length === 0) continue;
      items.push({
        type: 'service',
        name: service,
        description: `${serviceFiles.length} files`,
        children: serviceFiles.map(f => ({
          type: f.scriptType,
          name: f.path.split('/').pop(),
          path: f.path,
          description: f.description,
        })),
      });
    }

    return items;
  }
}

export const robloxExporter = new RobloxExporter();
